# -*- coding: utf-8 -*-
from . import models

def uninstall_hook(cr, registry):
    # Remove attachments (Excel reports) generated by this module to free disk space and avoid orphans
    cr.execute("DELETE FROM ir_attachment WHERE res_model = 'sold.unsold.products.report';")
    
    # Truncate tables first to quickly release storage space before dropping
    cr.execute("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'sold_unsold_products_report_line');")
    if cr.fetchone()[0]:
        cr.execute("TRUNCATE TABLE sold_unsold_products_report_line CASCADE;")
        
    cr.execute("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'sold_unsold_products_report');")
    if cr.fetchone()[0]:
        cr.execute("TRUNCATE TABLE sold_unsold_products_report CASCADE;")
        
    # Drop all created tables
    cr.execute("DROP TABLE IF EXISTS sold_unsold_products_report_line CASCADE;")
    cr.execute("DROP TABLE IF EXISTS sold_unsold_products_report CASCADE;")
    
    # Drop custom fields added to standard models
    cr.execute("ALTER TABLE product_product DROP COLUMN IF EXISTS internal_category CASCADE;")

